dependencies = []
description = "HTTP server that handle the download of the Scalingo CLI"
destination_server = ["scalingo-platform"]
flags = ["scalingo-app"]
languages = ["go"]
owner = "etienne@scalingo.com"
team = "IST"
version = "1.1.0"
