dependencies = []
description = "HTTP server that handles the download of the Scalingo CLI"
destination_server = ["scalingo-platform"]
flags = ["scalingo-app"]
languages = ["go", "github-actions"]
owner = "team-infrastructure-services@scalingo.com"
team = "IST"
tier = 1
version = "1.1.0"
